theme: jekyll-theme-cayman
title: ปฏิบัติการช่วยเหลือ 13 ชีวิตในถ้ำหลวง
description: รวบรวมข้อมูลข่าวสาร จากสื่อต่างๆ รวมถึงข้อมูลที่ผิดๆ และ FAQ เกี่ยวกับการช่วยเหลือทีมหมูป่าอะคาเดมี่ 13 คนที่ติดอยู่ในถ้ำหลวง
github:
  is_project_page: false
google_analytics: UA-121443271-2
collections:
  faq:
    output: true
    permalink: /:collection/:path/
  fakes:
    output: true
    permalink: /:collection/:path/
defaults:
  - scope:
      path: ""
      type: faq
    values:
      layout: category
  - scope:
      path: ""
      type: fakes
    values:
      layout: category